### ISSUE TITLE
Convert model to CoreML format

### ISSUE THREAD

**Issue by N-Harish** [1996scarlet/Dense-Head-Pose-Estimation#12]
@1996scarlet I am currently using the tflite model from your repo. I am running inference on a mac so I would like to convert the model into coreml (for Apple M1/M2) . Can you provide me the source model so that I can convert this into coreml format or suggest some ways to convert tflite to coreml ?

**Comment by 1996scarlet** [comment]
the training codes are very similar to [3DDFA_V2](https://github.com/cleardusk/3DDFA_V2), you can refer to that implementation.
