### ISSUE TITLE
FLAME instead of BFM

### ISSUE THREAD

**Issue by emlcpfx** [1996scarlet/Dense-Head-Pose-Estimation#13]
What would need to be changed to use the FLAME 3DMM instead of the BFM?

**Comment by 1996scarlet** [comment]
In my opinion, if you use flame instead of bfm, you need to retrain the network parameters using the annotated data and referring to the original paper.
But I do not recommend doing so. Why don't you consider modifying the network structure and writing a new paper based on flame?

**Comment by emlcpfx** [comment]
I’m far too dumb to do that, LOL.
