### ISSUE TITLE
MobileNet vs. ResNet

### ISSUE THREAD

**Issue by emlcpfx** [1996scarlet/Dense-Head-Pose-Estimation#14]
In the original 3DDFA_v2, one can choose to use MobileNet or Resnet. Resnet is slower, but gives better tracking results.

I can’t find anything in the code about that. Has that functionality been replaced with something different and/or better?

**Comment by 1996scarlet** [comment]
Yes, the focus of this implementation is on 3D face reconstruction in low computing power scenarios.
If you have a need to use ResNet as the backbone network, we will record it and provide a high-precision backbone network when time permits.
