### ISSUE TITLE
Landmark accuracy around the eyes.

### ISSUE THREAD

**Issue by AndresLopezE** [1996scarlet/Dense-Head-Pose-Estimation#6]
Does anyone have a problem with accuracy of landmarks around the eyes, like if i have my eyes fully open or fully closed, the landmarks wont change.

**Comment by 1996scarlet** [comment]
Actually, this is caused by the 300W-LP dataset.
There are only a few images with closed-eyes in the training data, so the landmarks of eyes are not very accurate.

You may refer to the [3DDFA_V2 FQA](https://github.com/cleardusk/3DDFA_V2#fqa) for more information.
