### ISSUE TITLE
How can i get Depth

### ISSUE THREAD

**Issue by joongkyunKim** [1996scarlet/Dense-Head-Pose-Estimation#7]
hi, 
I want to get information about the depth of the face, how do I calculate it?
i don't need rendering but only need depth map.
like 
https://github.kakaocorp.com/data-sci/3DDFA_V2_tf2/blob/master/utils/depth.py
thank you in advance!

**Comment by 1996scarlet** [comment]
The current model does not support outputting depth information (within camera coordinate)
However, you can use 3DDFA-V2, our training methods and data are the same, the only difference is the post-processing.
