### ISSUE TITLE
Where can I find the camera matrix params derived from the model for a given frame?

### ISSUE THREAD

**Issue by Tetsujinfr** [1996scarlet/Dense-Head-Pose-Estimation#9]
thanks

**Comment by Tetsujinfr** [comment]
Ok so I guess this is 
        self._get_camera_matrix = partial(self._interpreter.get_tensor,
                                          output_details[0]["index"])

in BaseTFLiteFaceAlignment ?

**Comment by 1996scarlet** [comment]
Yes, we can get the camera_matrix `R` directly from the model output.

https://github.com/1996scarlet/Dense-Head-Pose-Estimation/blob/60a5bdf3974746ae995b04cc4b23c8ac72f0c45d/service/TFLiteFaceAlignment.py#L29-L30

https://github.com/1996scarlet/Dense-Head-Pose-Estimation/blob/60a5bdf3974746ae995b04cc4b23c8ac72f0c45d/service/TFLiteFaceAlignment.py#L75-L82

Then, we can decompose matrix to ruler angle

https://github.com/1996scarlet/Dense-Head-Pose-Estimation/blob/60a5bdf3974746ae995b04cc4b23c8ac72f0c45d/service/__init__.py#L101-L111
